export const REQUEST_USER_DATA = 'REQUEST_USER_DATA'
export const SHOW_USER_DATA = 'SHOW_USER_DATA'
export const FAILED_GET_USER_DATA = 'FAILED_GET_USER_DATA'
export const SUCCESS_USER_DATA = 'SUCCESS_USER_DATA'